server:
  port: 9191
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/department-service/**
        - id: APPLICANT-SERVICE
          uri: lb://APPLICANT-SERVICE
          predicates:
            - Path=/applicant-service/**
        - id: UI-SERVICE
          uri: lb://UI-SERVICE
          predicates:
            - Path=/ui-service/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost